version: '3.8'

services:
  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - appnet
    environment:
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: test.sender.filghts.project@gmail.com
      SPRING_MAIL_PASSWORD: esjwfuudxnvywyha


  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
